### ISSUE TITLE
Makefile doesn't work on mac OSX when the compilation fails, probably regex's aren't consistent

### ISSUE THREAD

**Issue by glwhart** [rosenbrockc/fortpy#126]
When the compilation fails, sometimes the output is unusable or non-existent. I've spent some time trying to figure out the problem. It appears that the `grep` is failing when `ERROR` is populated in the makefile. I think it's because the regex syntax for marylou and mac are not compatible. It would be nice to update the makefile so that it works on both marylou and on mac.

**Comment by rosenbrockc** [comment]
Decided the `grep` wasn't necessary because when compilation fails, it is only for a single unit tests program executable. I originally snagged that error line from the `uncle` Makefile; it works there because `uncle` uses a set error "header" before writing errors, and it compiles multiple files simultaneously.

I just switched the `grep` for a `cat` and it makes it easy to see why the test compilation failed.

While I debug, I am working in the `debug` branch of the repo. If you check that one out (`git checkout debug` and then `pip install -e fortpy/` on the directory, you can run with the latest version until I finally push it to `pypi`.
