### ISSUE TITLE
Better output when compiling fortpy-created programs

### ISSUE THREAD

**Issue by glwhart** [rosenbrockc/fortpy#127]
When something goes wrong with a program that fortpy creates and it must be edited, recompiled, run, and debugged, the output isn't as helpful as it could be:
Apparently, the makefile expects that an environmental variable to be set, `FAM`, which indicates which compiler is to be targeted (gfortran, ifort, etc.), but if the user doesn't know to do this, the output doesn't help. It just says, 
```
(p2) GLWH:derivative_structure_generator.find_permutation_of_group.g hart$ make -f Makefile.find_permutation_of_group 
Makefile.find_permutation_of_group:13: Makefile.error: No such file or directory
make: *** No rule to make target `Makefile.error'.  Stop.
```
Also, in the case of segfaults, it would be nice to know how to change the makefile so that we get traceback. That's not really something directly related to this issue except that it accompanies the event.

I ended up using this to compile: ` make -f Makefile.find_permutation_of_group DEBUG=true` and this did change the compilation, but I still didn't get traceback info, even though I did a make clean. I'm not sure if this is gfortran's fault, something with the debug flags, or what.

**Comment by rosenbrockc** [comment]
I added one extra flag for debug optimizations `-Og` to the Makefile for `gfortran`. I also updated the Makefile so that you don't have to specify `F90` or `FAM` anymore as long as you are using `gfortran` and it exists on your path.

If you do specify `F90`, the compiler will be tested to see if it is of the `gfortran` family. If it is, then you don't need to specify `FAM` anymore either.

When `DEBUG=1` is specified, the appropriate flags are added for traceback. However, previously the compiler optimizations were sludging everything together, deleting local variables, etc. to optimize. The new `-Og` flag tries to get a good balance between optimization and debuggability.

After all of this, I still can't get any useful output when running unit test executables.

I did change `fortpy` so that output is not redirected when `debug=true`.
