### ISSUE TITLE
No Body in File Comparison Template

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#46]
If there isn't a body tag in an XML template, the code fails with divide by zero error on the `percent_match`. If we fix that, then it still reports only 50% match because the body is returning zero for all its comparisons. Body should be ignored if it isn't present in the template.

**Comment by rosenbrockc** [comment]
Fixed in Revision 1.5.7. Added some conditionals to prevent the divide by zero error. Also updated the `percent_match` and `common_match` properties for the aggregate types to check for actual data in the body. The printing for the detailed reports also indicates now whether a template excluded the body/preamble from comparison.
