### ISSUE TITLE
isense and xml vs other documentation standard

### ISSUE THREAD

**Issue by zbeekman** [rosenbrockc/fortpy#60]
I am very excited about and interested in fortpy’s Emacs integration. However, I have no need of a new unit testing framework or code documentation framework. I use the *excellent* [FORD](https://github.com/cmacmackin/ford) package to document all my new projects, and use either CMake’s testing framework, funit, or a simple shell script for unit testing. Also, I *LOATH* XML.

Here is my question:

> Would fortpy still be able to generate emacs completion information even if I don’t embed the XML descriptions? 

I don’t mind setting up some small XML project config files, but would prefer to minimize the amount of XML I have to write, and exclude it completely from my source code. I wonder how hard it would be to enable it to use the kind of documentation conventions FORD uses. (They are somewhat similar to Doxygen.)

**Comment by rosenbrockc** [comment]
Without the XML documentation, the isense should still provide completion for signatures of methods, variables etc. with in the scope where you are editing. The XML just provides text explanations for the parameters/variables etc. but it isn't required. So, yes the autocompletion should still work. Also, the built-in Fortran functions are completed documented already in fortpy and show up with parameter support etc.

I looked briefly at FORD and I like the simplicity of its implementation; the XML tags can be obstructive for run-of-the-mill parameters and variables that don't require anything except a text description. In those cases it would be easier to describe using FORD. Since it is coded in python, there are probably classes that describe the various code components etc. and it should be doable to match them up and copy the documentation over.

There are aspects of the XML that are necessary for completely automating the unit testing, but there is no reason why we couldn't mix the two documentation styles: use FORD-style documentation for almost everything and then use the XML for the other corner cases where it wouldn't be sufficient (for example nested XML tags).

For the short term I don't have time to do this right away; however, if you uncover any bugs in the autocomplete I could focus on those to get you up and running with basic code support.

**Comment by zbeekman** [comment]
Thanks for getting back to me! I’ll try out the Emacs/FortPy intellisense etc. sometime soon and let you know how it goes.

> the isense should still provide completion for signatures of methods, variables etc. with in the scope where you are editing

When you say “within the the scope you are editing” do you mean that it limits the completion to just the current file, or to the scope in the programming/Fortran sense of the word: All variables and procedures available through use association, etc.?

Also, I am no great emacs lisp programmer and have a number of other packages… I wonder if autocompletion, hippie expand and yasnippets will all play nice with FortPy… only one way to find out. 

Thanks so much for this cool project!

**Comment by zbeekman** [comment]
P.S. no rush on Ford integration… the descriptions of the variables in the call signature are not critical at all for me.

**Comment by rosenbrockc** [comment]
Yes, I mean within the programming scope. You will need to setup a global XML file to tell fortpy where all your libraries' source code is located. When you do an import with `use`, it will search first in the current project directory and then in any libraries located in your global config. The variables, subroutines, etc. that show up for autocomplete have to be within the current module or be public in one of the modules included with a `use` tag. 

The symbols available in each programming scope should work as you would expect them to.

**Comment by zbeekman** [comment]
great! Any hope of it figuring out what to do with overloaded interfaces, or is that asking too much?

**Comment by rosenbrockc** [comment]
It knows that they exist, but doesn't change its suggestion of signatures as you type extra parameters. At the moment, the signature of the interface for each parameter just shows all the possible types that it will accept in that position.

You are welcome to open an enhancement issue to give more ideas of how we could do it differently; we have complete flexibility in defining how it shows up.

**Comment by zbeekman** [comment]
oh, wow that sounds great! My last curiosity is about keyword calls, but I can try it out to find out. Thanks!
