### ISSUE TITLE
Auxread trying to access memory outside of allowed block.

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#78]
Whenever auxread is called the program either segfaults, returns malloc code 3, or an error of index is above upper bound of -2.

**Comment by rosenbrockc** [comment]
Some fixes applied in Revision 1.7.5. However, this is also caused by user error. `gfortran` treats an uninitialized pointer as an unknown state, thus:

```fortran
integer, pointer :: variable(:)
print *, associated(variable)
```

will print either `T` or `F` randomly. `ifort` sets them all to be unassociated if the user does nothing so that this is not an issue. A recent revision included a new script `bestprac.py` that scan code for these loose pointer references so they can be fixed. However, it relies on explicit `intent(out)` on the user-type variables for subroutines that alter them.

The problem is that for `intent(inout)`, it is possible that the variable already has a value for certain members of type `pointer`, so they shouldn't have that value changed. Only the developer will know if they should be setting an uninitialized pointer to `null()` in the subroutine or not.

After fixing the uninitialized pointer references, the unit tests run for all 76 cases without any segfaults.
